name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: Ashwini-Lokannavar/Triggeredwf/.github/workflows/backend.yml@v1

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: Ashwini-Lokannavar/Triggeredwf/.github/workflows/backend.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets..TEST_KEY }}
    
