# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: [self-hosted , 20v]

    steps:
    - name: step-1 - checkout to main branch from githun
      uses: actions/checkout@v2
     
    - name: Build with Maven
      run: |
       mvn -B clean package --file releaseservice/pom.xml 
       scp C:\actions-runner\_work\devops-rest-apis\devops-rest-apis\releaseservice\target\releaseservice-0.0.1-SNAPSHOT.jar GALILEO\svc_devops@svdthputws0010v:/TEMP
       
    - uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
          owner: Ashwini-Lokannavar
          repo: devops-rest-apis-postman
          github_token: ${{ secrets.TEST_KEY}}
          workflow_file_name: postamantest.yml
       
      
    
      
      
       
      
    
      
      

    
      
