name: Call a reusable workflows

on:
  push:
    branches:
      - main

jobs:
  
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: Ashwini-Lokannavar/Triggeredwf/.github/workflows/backend.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.TEST_KEY}}
