name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: [self-hosted , F1]

    steps:
    - name: step-1 - checkout to main branch from githun
      uses: actions/checkout@v2
     
   
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: Ashwini-Lokannavar/Triggeredwf/.github/workflows/backend.yml@main
    
     
    secrets:
      token: ${{ secrets.TEST_KEY}}
