name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: Ashwini-Lokannavar/Triggeredwf/.github/workflows/backend.yml@main
    
     
    secrets:
      token: ${{ secrets.TEST_KEY}}
